version: '3'
services:
  bidding_system:
    build: 
      context: .
      args:
        DATABASE_URL: "[mongo db url]"
        PORT: 5000
        NODE_ENV: "production"
        DJANGO_API_PORT: 8000
        DJANGO_API_TOKEN_VERIFICATION_URL: "http://127.0.0.1:8000/user/token/verify/"
    volumes:
      - .:/usr/src/bidding-system
    container_name: bidding-system-api-container
    restart: always
    ports:
      - 5000:5000
    command: bash -c /usr/src/bidding-system/start.sh
    env_file: .env