
version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/bidding-system
    container_name: bidding-system-api-container
    restart: always
    ports:
      - 5000:5000
    command: bash -c /usr/src/bidding-system/start.sh
    env_file: .env