name: Run tests with connection to Django and MongoDB

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        mongodb-version: ["6.0"]

    steps:
      - name: Checkout trading_api repo
        uses: actions/checkout@v3
        with:
          repository: M7011E-django-unchained-org/trading_api
          path: "./trading_api"

      - name: Update
        run: sudo apt update
        working-directory: ./trading_api

      - name: Install pip
        run: sudo apt install python3-pip
        working-directory: ./trading_api

      - name: Install requirements
        run: pip install -r requirements.txt
        working-directory: ./trading_api

      - name: Execute linting and tests
        env:
          DJANGO_SETTINGS_MODULE: trading_api.settings
        run: flake8 && python manage.py test
        working-directory: ./trading_api

      - name: Checkout main repo
        uses: actions/checkout@v3
        # with:
        #   path: main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: create env file
        run: |
          touch .env
          echo TEST_DATABASE_URL=${{ secrets.MONGO_TEST_DATABASE_URL }} >> .env

      - run: npm install

      - run: npm test
