name: Run tests with connection to Django and MongoDB

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        mongodb-version: ["6.0"]

    steps:
      # Checkout the Node.js project
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          path: main

      # Checkout the Django project
      - name: Checkout trading_api repo
        uses: actions/checkout@v3
        with:
          repository: M7011E-django-unchained/trading_api
          path: "./trading_api"

      # Set up Python
      - name: Update
        run: sudo apt update
        working-directory: ./trading_api

      - name: Install pip
        run: sudo apt install python3-pip
        working-directory: ./trading_api

      - name: Install Django project requirements
        run: pip install -r requirements.txt
        working-directory: ./trading_api

      - name: Execute Django project linting and tests
        env:
          DJANGO_SETTINGS_MODULE: trading_api.settings
        run: flake8 && python manage.py test
        working-directory: ./trading_api

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: create env file
        run: |
          touch .env
          echo TEST_DATABASE_URL=${{ secrets.MONGO_TEST_DATABASE_URL }} >> .env
          echo TEST_ON_GITHUB=true >> .env
        working-directory: ./main

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./main

      - name: Run Node.js tests
        run: npm test
        working-directory: ./main
